# **Practice Codes Feature Scaling**

In [ ]:
# import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

In [ ]:
wine = pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Wine.csv')

In [ ]:
wine.head()

class_label class_name  alcohol  malic_acid   ash  alcalinity_of_ash  \
0            1     Barolo    14.23        1.71  2.43               15.6   
1            1     Barolo    13.20        1.78  2.14               11.2   
2            1     Barolo    13.16        2.36  2.67               18.6   
3            1     Barolo    14.37        1.95  2.50               16.8   
4            1     Barolo    13.24        2.59  2.87               21.0   

   magnesium  total_phenols  flavanoids  nonflavanoid_phenols  \
0        127           2.80        3.06                  0.28   
1        100           2.65        2.76                  0.26   
2        101           2.80        3.24                  0.30   
3        113           3.85        3.49                  0.24   
4        118           2.80        2.69                  0.39   

   proanthocyanins  color_intensity   hue  od280  proline  
0             2.29             5.64  1.04   3.92     1065  
1             1.28             4.38  1.05   3.40     1050  
2             2.81             5.68  1.03   3.17     1185  
3             2.18             7.80  0.86   3.45     1480  
4             1.82             4.32  1.04   2.93      735

In [ ]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   class_label           178 non-null    int64  
 1   class_name            178 non-null    object 
 2   alcohol               178 non-null    float64
 3   malic_acid            178 non-null    float64
 4   ash                   178 non-null    float64
 5   alcalinity_of_ash     178 non-null    float64
 6   magnesium             178 non-null    int64  
 7   total_phenols         178 non-null    float64
 8   flavanoids            178 non-null    float64
 9   nonflavanoid_phenols  178 non-null    float64
 10  proanthocyanins       178 non-null    float64
 11  color_intensity       178 non-null    float64
 12  hue                   178 non-null    float64
 13  od280                 178 non-null    float64
 14  proline               178 non-null    int64  
dtypes: float64(11), int64(3

In [ ]:
wine.describe()

class_label     alcohol  malic_acid         ash  alcalinity_of_ash  \
count   178.000000  178.000000  178.000000  178.000000         178.000000   
mean      1.938202   13.000618    2.336348    2.366517          19.494944   
std       0.775035    0.811827    1.117146    0.274344           3.339564   
min       1.000000   11.030000    0.740000    1.360000          10.600000   
25%       1.000000   12.362500    1.602500    2.210000          17.200000   
50%       2.000000   13.050000    1.865000    2.360000          19.500000   
75%       3.000000   13.677500    3.082500    2.557500          21.500000   
max       3.000000   14.830000    5.800000    3.230000          30.000000   

        magnesium  total_phenols  flavanoids  nonflavanoid_phenols  \
count  178.000000     178.000000  178.000000            178.000000   
mean    99.741573       2.295112    2.029270              0.361854   
std     14.282484       0.625851    0.998859              0.124453   
min     70.000000       0.980000    0.340000              0.130000   
25%     88.000000       1.742500    1.205000              0.270000   
50%     98.000000       2.355000    2.135000              0.340000   
75%    107.000000       2.800000    2.875000              0.437500   
max    162.000000       3.880000    5.080000              0.660000   

       proanthocyanins  color_intensity         hue       od280      proline  
count       178.000000       178.000000  178.000000  178.000000   178.000000  
mean          1.590899         5.058090    0.957449    2.611685   746.893258  
std           0.572359         2.318286    0.228572    0.709990   314.907474  
min           0.410000         1.280000    0.480000    1.270000   278.000000  
25%           1.250000         3.220000    0.782500    1.937500   500.500000  
50%           1.555000         4.690000    0.965000    2.780000   673.500000  
75%           1.950000         6.200000    1.120000    3.170000   985.000000  
max           3.580000        13.000000    1.710000    4.000000  1680.000000

In [ ]:
wine.columns

Index(['class_label', 'class_name', 'alcohol', 'malic_acid', 'ash',
       'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids',
       'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue',
       'od280', 'proline'],
      dtype='object')

In [ ]:
X = wine.drop(['class_label', 'class_name'], axis=1)

## **Standard Scaler**

In [ ]:
X

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6        127           2.80   
1      13.20        1.78  2.14               11.2        100           2.65   
2      13.16        2.36  2.67               18.6        101           2.80   
3      14.37        1.95  2.50               16.8        113           3.85   
4      13.24        2.59  2.87               21.0        118           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5         95           1.68   
174    13.40        3.91  2.48               23.0        102           1.80   
175    13.27        4.28  2.26               20.0        120           1.59   
176    13.17        2.59  2.37               20.0        120           1.65   
177    14.13        4.10  2.74               24.5         96           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280  proline  
0     3.92     1065  
1     3.40     1050  
2     3.17     1185  
3     3.45     1480  
4     2.93      735  
..     ...      ...  
173   1.74      740  
174   1.56      750  
175   1.56      835  
176   1.62      840  
177   1.60      560  

[178 rows x 13 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit_transform(X)
#ss.transform(X)

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
mm.fit(X)
mm.transform(X)

array([[0.84210526, 0.1916996 , 0.57219251, ..., 0.45528455, 0.97069597,
        0.56134094],
       [0.57105263, 0.2055336 , 0.4171123 , ..., 0.46341463, 0.78021978,
        0.55064194],
       [0.56052632, 0.3201581 , 0.70053476, ..., 0.44715447, 0.6959707 ,
        0.64693295],
       ...,
       [0.58947368, 0.69960474, 0.48128342, ..., 0.08943089, 0.10622711,
        0.39728959],
       [0.56315789, 0.36561265, 0.54010695, ..., 0.09756098, 0.12820513,
        0.40085592],
       [0.81578947, 0.66403162, 0.73796791, ..., 0.10569106, 0.12087912,
        0.20114123]])

In [ ]:
from sklearn.preprocessing import StandardScaler
ss =StandardScaler()

In [ ]:
ss.fit_transform(X)

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [ ]:
pd.DataFrame(ss.fit_transform(X)).describe()

0             1             2             3             4   \
count  1.780000e+02  1.780000e+02  1.780000e+02  1.780000e+02  1.780000e+02   
mean  -8.382808e-16 -1.197544e-16 -8.370333e-16 -3.991813e-17 -3.991813e-17   
std    1.002821e+00  1.002821e+00  1.002821e+00  1.002821e+00  1.002821e+00   
min   -2.434235e+00 -1.432983e+00 -3.679162e+00 -2.671018e+00 -2.088255e+00   
25%   -7.882448e-01 -6.587486e-01 -5.721225e-01 -6.891372e-01 -8.244151e-01   
50%    6.099988e-02 -4.231120e-01 -2.382132e-02  1.518295e-03 -1.222817e-01   
75%    8.361286e-01  6.697929e-01  6.981085e-01  6.020883e-01  5.096384e-01   
max    2.259772e+00  3.109192e+00  3.156325e+00  3.154511e+00  4.371372e+00   

               5             6             7             8             9   \
count  178.000000  1.780000e+02  1.780000e+02  1.780000e+02  1.780000e+02   
mean     0.000000 -3.991813e-16  3.592632e-16 -1.197544e-16  2.494883e-17   
std      1.002821  1.002821e+00  1.002821e+00  1.002821e+00  1.002821e+00   
min     -2.107246 -1.695971e+00 -1.868234e+00 -2.069034e+00 -1.634288e+00   
25%     -0.885468 -8.275393e-01 -7.401412e-01 -5.972835e-01 -7.951025e-01   
50%      0.095960  1.061497e-01 -1.760948e-01 -6.289785e-02 -1.592246e-01   
75%      0.808997  8.490851e-01  6.095413e-01  6.291754e-01  4.939560e-01   
max      2.539515  3.062832e+00  2.402403e+00  3.485073e+00  3.435432e+00   

                 10            11            12  
count  1.780000e+02  1.780000e+02  1.780000e+02  
mean   1.995907e-16  3.193450e-16 -1.596725e-16  
std    1.002821e+00  1.002821e+00  1.002821e+00  
min   -2.094732e+00 -1.895054e+00 -1.493188e+00  
25%   -7.675624e-01 -9.522483e-01 -7.846378e-01  
50%    3.312687e-02  2.377348e-01 -2.337204e-01  
75%    7.131644e-01  7.885875e-01  7.582494e-01  
max    3.301694e+00  1.960915e+00  2.971473e+00

## **Min Max Scaler**

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()

In [ ]:
mm.fit_transform(X)

array([[0.84210526, 0.1916996 , 0.57219251, ..., 0.45528455, 0.97069597,
        0.56134094],
       [0.57105263, 0.2055336 , 0.4171123 , ..., 0.46341463, 0.78021978,
        0.55064194],
       [0.56052632, 0.3201581 , 0.70053476, ..., 0.44715447, 0.6959707 ,
        0.64693295],
       ...,
       [0.58947368, 0.69960474, 0.48128342, ..., 0.08943089, 0.10622711,
        0.39728959],
       [0.56315789, 0.36561265, 0.54010695, ..., 0.09756098, 0.12820513,
        0.40085592],
       [0.81578947, 0.66403162, 0.73796791, ..., 0.10569106, 0.12087912,
        0.20114123]])

In [ ]:
pd.DataFrame(mm.fit_transform(X)).describe()

0           1           2           3           4           5   \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     0.518584    0.315484    0.538244    0.458502    0.323278    0.453487   
std      0.213639    0.220780    0.146708    0.172142    0.155244    0.215811   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.350658    0.170455    0.454545    0.340206    0.195652    0.262931   
50%      0.531579    0.222332    0.534759    0.458763    0.304348    0.474138   
75%      0.696711    0.462945    0.640374    0.561856    0.402174    0.627586   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               6           7           8           9           10          11  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     0.356386    0.437460    0.372523    0.322363    0.388170    0.491460   
std      0.210730    0.234818    0.180555    0.197806    0.185831    0.260070   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.182489    0.264151    0.264984    0.165529    0.245935    0.244505   
50%      0.378692    0.396226    0.361199    0.290956    0.394309    0.553114   
75%      0.534810    0.580189    0.485804    0.419795    0.520325    0.695971   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               12  
count  178.000000  
mean     0.334446  
std      0.224613  
min      0.000000  
25%      0.158702  
50%      0.282097  
75%      0.504280  
max      1.000000